# Generated by Django 5.1.1 on 2024-10-30 02:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_admin', models.CharField(max_length=100)),
                ('email_admin', models.EmailField(max_length=254, unique=True)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_bergabung', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Konsumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_konsumen', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('tanggal_registrasi', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_member', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15, null=True)),
                ('status_member', models.CharField(choices=[('Aktif', 'Aktif'), ('Nonaktif', 'Nonaktif')], default='Aktif', max_length=10)),
                ('tanggal_bergabung', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('deskripsi_produk', models.TextField(blank=True, null=True)),
                ('kategori_produk', models.CharField(blank=True, max_length=50, null=True)),
                ('harga_produk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok_produk', models.IntegerField()),
                ('tanggal_ditambahkan', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_laporan', models.CharField(max_length=50)),
                ('tanggal_laporan', models.DateField(default=django.utils.timezone.now)),
                ('isi_laporan', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='Platfrom_E_commerce_mobile.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Pesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_pesan', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesan', to='Platfrom_E_commerce_mobile.admin')),
                ('pengirim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='Platfrom_E_commerce_mobile.member')),
            ],
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_produk', models.IntegerField()),
                ('tanggal_ditambahkan', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keranjang', to='Platfrom_E_commerce_mobile.member')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keranjang', to='Platfrom_E_commerce_mobile.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_transaksi', models.DateField(default=django.utils.timezone.now)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metode_pembayaran', models.CharField(choices=[('Transfer', 'Transfer'), ('Kartu Kredit', 'Kartu Kredit'), ('COD', 'COD')], max_length=15)),
                ('status_pembayaran', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas')], max_length=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='Platfrom_E_commerce_mobile.member')),
            ],
        ),
    ]
