# Generated by Django 5.1.1 on 2024-09-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matkul', models.CharField(max_length=120, null=True)),
                ('jurusan', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
